-- Limpa os dados e mantem a estrutura

TRUNCATE TABLE pagamentos RESTART IDENTITY CASCADE;
TRUNCATE TABLE consultas RESTART IDENTITY CASCADE;
TRUNCATE TABLE profissionais RESTART IDENTITY CASCADE;
TRUNCATE TABLE pacientes RESTART IDENTITY CASCADE;